version: "3.8"

services:
  db:
    image: postgres:14
    restart: always
    container_name: startify_db
    environment:
      POSTGRES_USER: startify_user
      POSTGRES_PASSWORD: startify_pass
      POSTGRES_DB: startify_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
